### ISSUE TITLE
The tool stop working due to Github changes

### ISSUE THREAD

**Issue by hdoan741** [jlebar/git-pr-chain#4]
1. `gh` tool moves the place it stores `oauth_token` to `config/hosts.yml`. The structure also looks a bit different now .
2. Even after I fix that, I hit an unknown error with `git pr-chain push` and I don't know how to fix it. My changes are clean rebase on top of the master branch. I hope this is not because github has tighten control of 3rd party API.
```
Creating PR for hdoan/add_password_version_to_parent_infos_tab_9e44, base master...
Traceback (most recent call last):
  File "/home/dev/bin/git-pr-chain", line 857, in <module>
    main()
  File "/home/dev/bin/git-pr-chain", line 853, in main
    args.func(args)
  File "/home/dev/bin/git-pr-chain", line 663, in cmd_push
    create_and_update_prs(args)
  File "/home/dev/bin/git-pr-chain", line 613, in create_and_update_prs
    pr = repo.create_pull(title=title, base=base, head=branch, body="")
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.4/lib/python3.9/site-packages/github/Repository.py", line 1347, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.4/lib/python3.9/site-packages/github/Repository.py", line 1378, in __create_pull_1
    return self.__create_pull(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.4/lib/python3.9/site-packages/github/Repository.py", line 1391, in __create_pull
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.4/lib/python3.9/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.4/lib/python3.9/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "PullRequest", "field": "head", "code": "invalid"}], "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

**Comment by jlebar** [comment]
Oh no!

I'm sorry to hear that this has stopped working.

TBH I'm not actively using this right now, so I don't have a test setup onhand.  Whatever is going on, surely there's a way to create PRs from the CLI, because plenty of tools still do that.  My guess is that maybe the "validation failed" error has something to do with the oauth business.

@jkff are you still using this tool?

**Comment by jkff** [comment]
Nope, currently not using.
